### ISSUE TITLE
Document icons (iron-iconset and font icons)

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#36] opened 2017-11-24 17:44 UTC
Valo icons are few but considerably better-looking than `vaadin-icons` 😃  Seems like there's no demo page to see all of them at once, though. It would be really useful!

**Comment by jouni** [comment] 2017-11-24 20:40
True, no demo yet.

We need to come up with a plan how our icons will evolve. Like you said, the current vaadin-icons set doesn’t really work stylistically with the new Valo theme. But, I’m a bit hesitant in supporting two separate libraries.

So, I’m thinking if the current Valo icons could be the starting point of “vaadin-icons 2.0” (not the technical version, but the stylistic version). The problem is that we don’t really have much bandwidth in fleshing out the set right now. And currently there’s only a mere 23 icons from various categories. They are mostly the result of the Sketch mockups I’ve drawn mockup screens of the theme.

**Comment by web-padawan** [comment] 2018-01-19 19:05
Starting from the Lumo styles `v1.0.0-alpha3` release, all the icons are [visible and documented](https://cdn-origin.vaadin.com/vaadin-lumo-styles/1.0.0-alpha3/demo/icons.html) so I'm closing this issue.

**Closed as completed by web-padawan** 2018-01-19 19:05 UTC

**Comment by jouni** [comment] 2018-01-19 19:11
Yeah, thanks! I was going to close this, but forgot about it. 

As I spoke about ”a plan” above: the current plan is to keep this icon set separate from the existing vaadin icons set. No big plans yet for expanding the set, but it’s an option if there’s demand for it.
