### ISSUE TITLE
Styles are not imported if no web component is present in the DOM

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-valo-theme#44] opened 2017-12-22 13:08 UTC
I created an empty flow app with just some DIVs and native HTML, and imported the Valo theme. The theme (typography, colors) isn't applied until I also add e.g. a vaadin-button to the DOM.

**Comment by jouni** [comment] 2017-12-22 13:15
> and imported the Valo theme

How?

**Comment by tmattsso** [comment] 2017-12-22 13:17
`@HtmlImport("frontend://styles.html")`
and

```html
<!-- Adding Valo theme for vaadin-button -->
<link rel="import" href="bower_components/vaadin-valo-theme/vaadin-button.html">
<link rel="import" href="bower_components/vaadin-valo-theme/vaadin-text-field.html">
```
```html
<custom-style>
    <!-- This is where your App's styling should go. You can use .css files too. -->
    <style include="valo-colors valo-typography">
        html,
        body {
            height: auto;
        }
    </style>
</custom-style>
```

and 
```xml
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>vaadin-valo-theme</artifactId>
		</dependency>
```

**Comment by jouni** [comment] 2017-12-22 13:20
You forgot to actually import (!= include) the style modules.

So add the following HTML imports as well:

```html
<link rel="import" href="vaadin-valo-styles/color.html">
<link rel="import" href="vaadin-valo-styles/typography.html">
```

Most elements import those, that’s why you only get the styles when you include one or more elements.

**Comment by tmattsso** [comment] 2017-12-22 13:22
nope, didn't work. is that some other maven import, perhaps?

**Comment by jouni** [comment] 2017-12-22 13:22
I also encourage you to update to the latest Vaadin element versions and change from `vaadin-valo-theme` to `vaadin-valo-styles`, so you can drop the extra element theme imports.

**Comment by jouni** [comment] 2017-12-22 13:23
> nope, didn't work. is that some other maven import, perhaps?

Those are included in the `vaadin-valo-theme` package root. I assume you used correct urls for those.

**Comment by jouni** [comment] 2017-12-22 13:23
Oh, sorry, I accidentally used `vaadin-valo-styles` in my first example, and you are “still” using `vaadin-valo-theme`.

**Comment by tmattsso** [comment] 2017-12-22 13:24
I now have this, no errors and no worky:
```
<link rel="import" href="bower_components/vaadin-valo-theme/vaadin-button.html">
<link rel="import" href="bower_components/vaadin-valo-theme/vaadin-text-field.html">
<link rel="import" href="bower_components/vaadin-valo-theme/color.html">
<link rel="import" href="bower_components/vaadin-valo-theme/typography.html">
```

**Comment by jouni** [comment] 2017-12-22 13:27
And you still have

```html
<custom-style>
  <style include="valo-color valo-typography"></style>
</custom-style>
```

in your index.html (or root level of the document)?

**Comment by tmattsso** [comment] 2017-12-22 13:27
its in styles.html, which is imported.

**Comment by jouni** [comment] 2017-12-22 13:30
Hmm… the next obvious reason is that `custom-style` is not registered, and you should import that explicitly in your styles.html as well. You can find it from `bower_components/polymer/lib/elements/custom-style.html`.

**Comment by tmattsso** [comment] 2017-12-22 13:32
loaded that, still doesn't work :)

**Comment by heruan** [comment] 2017-12-22 13:49
Maybe I didn't understand what the issue is, but it's importing Valo styles works pretty well for me, see e.g. https://jsfiddle.net/heruan/5mgt4j05/

On the Flow side, AFAIK there's an heavy refactoring for including Valo by default and not all the components are up-to-date, so I wouldn't worry until all releases are in-sync.

**Comment by tmattsso** [comment] 2018-01-03 14:36
This is specifically when using the theme through Flow, yes. I guess I'll wait for that refactoring, then.

**Comment by jouni** [comment] 2018-01-23 12:24
Closing. Please reopen in https://github.com/vaadin/vaadin-lumo-styles if it’s still relevant.

**Closed as completed by jouni** 2018-01-23 12:24 UTC
