### ISSUE TITLE
vaadin-button jumps on hover

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-valo-theme#30] opened 2017-11-14 12:15 UTC
When using vaadin-valo-theme for `vaadin-button`s, hovering over a button causes it to shift down:
![valo-theme-button-jumping](https://user-images.githubusercontent.com/22416150/32779369-26e0a028-c946-11e7-9e34-08adfceeaed6.gif)

Here is a JS fiddle: https://jsfiddle.net/wths1wmv/

**Comment by jouni** [comment] 2017-11-14 12:27
Looks like a regression/feature in Chrome 62. Didn’t happen with Chrome 61.

**Comment by heruan** [comment] 2017-11-24 17:46
I'm experiencing this having the button mis-aligned on page load, adjusting itself upon hovering.

**Comment by jouni** [comment] 2017-11-25 21:02
If anyone has any clues how to fix this, I would really appreciate it!

**Comment by web-padawan** [comment] 2017-11-25 21:22
I played with the jsfiddle a bit, and it seems that this behavior is caused by `align-items: center` rule affecting pseudo elements. Is that rule ever needed? If we want to apply styles to the native button, we probably should target corresponding part instead (it currently inherits browser style).

**Comment by jouni** [comment] 2017-11-26 20:48
Thanks for the investigation! 

I think I actually accidentally fixed this when cleaning up the styles, by removing the unnecessary flexbox styles from the host. I tried restoring those styles, and the issue comes back. So I’m pretty confident this is fixed.

Fixed in bbd5783566e703a0cde75faad746a60b602fd218

**Closed as completed by jouni** 2017-11-26 20:48 UTC
