### ISSUE TITLE
importing Valo theme for vaadin-text-field crashes the page in the latest Edge

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-valo-theme#45] opened 2017-12-29 11:47 UTC
Using a Valo-themed vaadin-text-field crashes the entire web page in the latest released Edge version (possibly a browser bug).

Screen cast of the issue: https://youtu.be/PPb9n004GBQ
JS Fiddle (last known working version): https://jsfiddle.net/mg6gbq20/2/
JS Fiddle (first known broken version): https://jsfiddle.net/mg6gbq20/1/
JS Fiddle (the latest released version is still broken): https://jsfiddle.net/mg6gbq20/3/

**Comment by Haprog** [comment] 2018-01-11 07:20
In the description above by @vlukashov the "last known working version" JS Fiddle uses `alpha3` and the "first known broken version" uses `alpha5` so I wondered what about `alpha4`?

I just forked the JS Fiddle and tested on latest Edge and it seems that `alpha4` also works so it broke on update from `alpha4` to `alpha5`.

**Comment by Haprog** [comment] 2018-01-11 07:33
Here's a link to a compare view of those two tags: https://github.com/vaadin/vaadin-valo-styles/compare/v2.0.0-alpha4...v2.0.0-alpha5

**Comment by web-padawan** [comment] 2018-01-11 07:39
Broken in 24a001b by using `mask-image` CSS property (the prefixed version `-webkit-mask-image` does not affect Edge, at least the demo page can be loaded). I investigate if this is related to the CSS custom property used as value and will try to provide a reduced test case.

**Comment by Haprog** [comment] 2018-01-11 08:28
I did some testing with a simple fiddle. Looks like the problem is setting any value for `mask-image` using `var()`.

This very simple HTML+CSS only fiddle fails.
https://jsfiddle.net/Haprog/e9vq281m/7/

But if you set the `mask-image` value directly without `var()` then it doesn't crash.

**Comment by Haprog** [comment] 2018-01-11 08:33
It doesn't even matter if the CSS custom property is set or not. Just having

```css
.foo { mask-image: var(--foo); }
```
apply to any element will crash the page in Edge.

**Comment by web-padawan** [comment] 2018-01-11 08:34
@Haprog thank you for your effort. I came to the same conclusion eventually. Will submit a PR to the `vaadin-text-field` repo where this CSS is now applied for workaround, and probably check if there is a bug in the MS Edge tracker later.

**Comment by Haprog** [comment] 2018-01-11 08:35
Thanks!

**Comment by web-padawan** [comment] 2018-01-11 08:40
BTW this also happens for at least [clip-path](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11975071/) CSS property as well. So there might probably exist a more common bug with interpolating custom CSS properties as values for unsupported suff.

**Comment by Haprog** [comment] 2018-01-11 08:58
Inspired by https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8865594/ I tried `mask-image: unset;` also crashes Edge.

**Comment by Haprog** [comment] 2018-01-11 09:08
@web-padawan If you implement the workaround/fix to remove `var()` usage in `mask-image` please check for usage of `var()` in `mask-image` everywhere in the repo, not just in `vaadin-text-field` theme. I think there are at least few other place where it's used also.

**Comment by web-padawan** [comment] 2018-01-11 09:10
@Haprog see vaadin/vaadin-text-field#189 for my current approach. Basically the Firefox is the only browser supporting this property without the prefixes so far. Of course I will check all the other elements as well.

**Comment by Haprog** [comment] 2018-01-11 09:10
Doing some grepping in the `alpha5` commit I found:
```
./vaadin-tabs.html:59:         mask-image: var(--_valo-tabs-overflow-mask-image);
./menu-overlay.html:54:        mask-image: var(--_valo-menu-overlay-mask-image);
./vaadin-grid.html:144:        mask-image: var(--_valo-grid-cell-overflow-mask-image);
./vaadin-text-field.html:81:   mask-image: var(--_valo-text-field-overflow-mask-image);
```

**Comment by web-padawan** [comment] 2018-01-11 09:28
I submitted the PRs for elements. But [this line](https://github.com/vaadin/vaadin-valo-styles/blob/master/mixins/menu-overlay.html#L42) in the repo still fails even though the `@supports` directive is used, apparently that directive fails itself. This in particular causes `vaadin-dropdown-menu` demo page to crash (and all the other elements using same `menu-overlay.html` mixin as well).

/cc @jouni

**Comment by jouni** [comment] 2018-01-11 09:29
So Edge crashes on the `@supports` directive as well, when `mask-image` is used inside it?

**Comment by jouni** [comment] 2018-01-11 09:31
I think that particular code could be simplified, and instead of overlaying a pseudo element that creates the gradient, just use a mask image on the `[part="content"]` instead (with the same workarounds as in the other cases).

That way we can avoid using `@supports`.

**Comment by web-padawan** [comment] 2018-01-11 09:40
I'm still trying to confirm if the `@supports` directive fails and at least with `mask-image: unset` it does but the normal gradient value seems not to cause it, which I'm a bit confused about. But yes, we probably could simplify this code as you suggest.

**Comment by Haprog** [comment] 2018-01-11 09:44
In these cases the custom property value isn't even overridable by the user since it's defined right before use in the same selector, am I right?

Then we could just avoid the problem by not using the CSS custom property for mask-image, but just giving it the final value. The only downside is that the same value is duplicated for `-webkit-mask-image`.

Or is the custom property needed for some child elements by inheritance?

**Comment by jouni** [comment] 2018-01-11 09:46
@Haprog, that’s correct. I’ve only been trying to make maintenance a little easier by reducing copy-pasting the actual value. In vaadin-tabs the benefit is most obvious.

**Comment by jouni** [comment] 2018-01-11 09:47
@web-padawan, actually, if we move the mask-image to the `content` part, then we will have to make that the scrolling element as well. That’s probably the reasons I chose to do it this way.

**Comment by Haprog** [comment] 2018-01-11 10:00
I forked the repo and made a `legacy` branch and tagged `v2.0.0-alpha5.1` where I fixed this the easy way as currently we're still depending on the legacy alpha5 for the website and wanted to fix Edge for us asap.
https://github.com/Haprog/vaadin-valo-styles/commit/66bd3955a8cf051720724b16198be606f2103bcf

**Comment by jouni** [comment] 2018-01-11 12:33
For future reference, this does not affect versions of EdgeHTML before v15 where CSS custom properties are not supported.

**Comment by web-padawan** [comment] 2018-01-11 18:48
Here is the MS Edge [issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15415089/) to follow, which I already mentioned in comments for each of the PRs.

**Comment by vicsstar** [comment] 2018-01-15 09:30
This issue is happening for the latest release of `vaadin-grid` here: https://cdn.vaadin.com/vaadin-grid/5.0.0-alpha4/demo/#grid-basic-demos

**Comment by tomivirkki** [comment] 2018-01-15 09:31
5.0.0-alpha5 is the latest (tag)

**Comment by vicsstar** [comment] 2018-01-15 09:37
Yes never mind that. Was reviewing another PR and noticed the issue on IE/Edge. Checked the releases and didn't notice the greyed out (latest) release at the top (the boldest one at the top stood out).

Closing....

**Closed as completed by vicsstar** 2018-01-15 09:37 UTC
Labels: issue
